import type { Metadata } from "next"
import "./globals.css"
import { cn } from "@/lib/utils"
import { Nunito } from "next/font/google"
import ReactQueryProvider from "@/components/provider/ReactQueryProvider"
import ThemeProvider from "@/components/provider/ThemeProvider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const font = Nunito({
  subsets: ["latin"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("flex h-screen flex-col", font.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
